[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableStaticServing = true

[client]
toolbarMode = "minimal"
showSidebarNavigation = true

[pages]
"pages/01_Calendar_and_Journal.py" = "Calendar & Journal" 